services:
  postgres:
    image: postgres:16
    container_name: registry-postgres

    environment:
      POSTGRES_USER: registryuser
      POSTGRES_PASSWORD: registrypass
      POSTGRES_DB: registrydb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: likith0129/registry-tracker:latest

    container_name: registry-tracker-app

    ports:
      - "8081:8081"

    environment:
      DATABASE_URL: host=postgres user=registryuser password=registrypass dbname=registrydb port=5432 sslmode=disable

    depends_on:
      - postgres

volumes:
  postgres_data:
